---
Name: 'e-collector'
---
# Member:
#   extensions:
#     - StoredCreditcardExtension
Leochenftw\eCommerce\eCollector:
  DefaultCurrency: 'NZD'
  GSTRate: 0.15
  MerchantSettings:
    # MerchantHomepageURL: "https://www.nzyogo.co.nz"
    SuccessURL: "/checkout/success"
    FailureURL: "/checkout/fail"
    CancellationURL: "/checkout/cancel"
    CardSavedURL: "/checkout/saved"
    PaymentScheduledURL: "/checkout/pending"
  API:
    POLi: 'https://poliapi.apac.paywithpoli.com/api/v2/Transaction'
    Paystation: 'https://www.paystation.co.nz/direct/paystation.dll'
    PaystationLookup: 'https://payments.paystation.co.nz/lookup/'
    DPS : 'https://uat.paymentexpress.com/pxaccess/pxpay.aspx'
  GatewaySettings:
    POLi:
        CERT: '/var/www/ca-bundle.crt'
    Paystation:
        paystation: '_empty'
        pstn_gi: 'PAYSTATION'
        pstn_nr: 't'
  AdditionalSettings:
    Paystation:
      QuickMode: 1
Leochenftw\eCommerce\eCollector\Payment\Payment:
  payment_methods:
    DPS : DPS
    POLi : POLi
    Paystation : Paystation
    Invoice: Invoice
    DirectDebit: Direct Debit

SilverStripe\Security\Group:
  extensions:
    - Leochenftw\eCommerce\eCollector\Extensions\MemberGroupExtension

SilverStripe\CMS\Model\SiteTree:
  hide_ancestor: 'Leochenftw\eCommerce\eCollector\Model\Product'

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Leochenftw\eCommerce\eCollector\Extensions\SiteconfigExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Leochenftw\eCommerce\eCollector\Extensions\CustomButtonWorkAround
Leochenftw\eCommerce\eCollector\Model\Order:
  default_buttons:
    send_invoice    :   true
    cheque_cleared  :   true
    refund          :   true
    send_tracking   :   true
    debit_cleared   :   true

Leochenftw\eCommerce\eCollector\Model\Freight:
  allowed_countries:
    Domestic:
      nz: New Zealand
    Zone A:
      au: Australia
    Zone B:
      ck: Cook Islands
      fj: Fiji
      nc: New Caledonia
      ws: Samoa
      to: Tonga
      vu: Vanuatu
    Zone C:
      kh: Cambodia
      ca: Canada
      cn: China
      hk: Hong Kong
      in: India
      id: Indonesia
      jp: Japan
      kr: South Korea
      lk: Sri Lanka
      mo: Macau
      my: Malaysia
      ph: Philippines
      sg: Singapore
      tw: Taiwan
      th: Thailand
      us: United States
      vn: Vietnam
    Zone D:
      at: Austria
      be: Belgium
      hr: Croatia
      cz: Czech Republic
      dk: Denmark
      ec: Ecuador
      fi: Finland
      fr: France
      de: Germany
      gr: Greece
      hu: Hungary
      ie: Ireland
      it: Italy
      nl: Netherlands
      no: Norway
      pl: Poland
      pt: Portugal
      ro: Romania
      si: Slovenia
      es: Spain
      se: Sweden
      ch: Switzerland
      gb: United Kingdom
    Zone E:
      br: Brazil
      cl: Chile
      cr: Costa Rica
      sv: El Salvador
      mx: Mexico
      uy: Uruguay

---
Only:
  environment: 'dev'
---
Leochenftw\eCommerce\eCollector:
  GatewaySettings:
    Paystation:
      pstn_tm: 't'

---
Only:
  environment: 'live'
---
Leochenftw\eCommerce\eCollector:
  API:
    DPS : 'https://sec.paymentexpress.com/pxaccess/pxpay.aspx'
