---
Name: 'e-collector'
---
# Member:
#   extensions:
#     - StoredCreditcardExtension
Leochenftw\eCommerce\eCollector:
  DefaultCurrency: 'NZD'
  GSTRate: 0.15
  MerchantSettings:
    # MerchantHomepageURL: "https://www.nzyogo.co.nz"
    SuccessURL: "/checkout/success"
    FailureURL: "/checkout/fail"
    CancellationURL: "/checkout/cancel"
    CardSavedURL: "/checkout/saved"
    PaymentScheduledURL: "/checkout/pending"
  API:
    POLi: 'https://poliapi.apac.paywithpoli.com/api/v2/Transaction'
    Paystation: 'https://www.paystation.co.nz/direct/paystation.dll'
    PaystationLookup: 'https://payments.paystation.co.nz/lookup/'
    DPS : 'https://uat.paymentexpress.com/pxaccess/pxpay.aspx'
  GatewaySettings:
    POLi:
        CERT: '/var/www/ca-bundle.crt'
    Paystation:
        paystation: '_empty'
        pstn_gi: 'PAYSTATION'
        pstn_nr: 't'
  AdditionalSettings:
    Paystation:
      QuickMode: 1
Leochenftw\eCommerce\eCollector\Payment\Payment:
  payment_methods:
    DPS : DPS
    POLi : POLi
    Paystation : Paystation
    Invoice: Invoice
    DirectDebit: Direct Debit

SilverStripe\Security\Group:
  extensions:
    - Leochenftw\eCommerce\eCollector\Extensions\MemberGroupExtension

SilverStripe\CMS\Model\SiteTree:
  hide_ancestor: 'Leochenftw\eCommerce\eCollector\Model\Product'

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Leochenftw\eCommerce\eCollector\Extensions\SiteconfigExtension

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Leochenftw\eCommerce\eCollector\Extensions\CustomButtonWorkAround
Leochenftw\eCommerce\eCollector\Model\Order:
  default_buttons:
    send_invoice    :   true
    cheque_cleared  :   true
    refund          :   true
    send_tracking   :   true
    debit_cleared   :   true

---
Only:
  environment: 'dev'
---
Leochenftw\eCommerce\eCollector:
  GatewaySettings:
    Paystation:
      pstn_tm: 't'

---
Only:
  environment: 'live'
---
Leochenftw\eCommerce\eCollector:
  API:
    DPS : 'https://sec.paymentexpress.com/pxaccess/pxpay.aspx'
