---
Name: e-collector-routes
#After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'e-collector/poli-complete': 'Leochenftw\eCommerce\eCollector\Controller\PoliController'
    'e-collector/paystation-complete': 'Leochenftw\eCommerce\eCollector\Controller\PaystationController'
    'e-collector/dps-complete': 'Leochenftw\eCommerce\eCollector\Controller\DPSController'
    cart/$second/$third: Leochenftw\eCommerce\eCollector\Controller\CartController
    checkout/$status: Leochenftw\eCommerce\eCollector\Controller\CheckoutController
